//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;

    public class Employee
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DtBirth { get; set; }
        public string TabNumber { get; set; }
        public System.DateTime DtHire { get; set; }
        public string Gender { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Position { get; set; }
        public string Information { get; set; }
        public Nullable<int> IsActive { get; set; }

        //public virtual Department Department { get; set; }
    }
}
